version: '3.1'
networks:
  main:
services:
  redboxportal:
    build: .
    image: qcifengineering/redbox-portal:latest
    ports:
      - "1500:1500"
    user: node
    volumes:
      - ".:/opt/redbox-portal:delegated"
      - "./dev/attachments:/attachments:delegated"
      - "./dev/publication:/publication:delegated"
      - "./dev/hooks:/opt/hooks:delegated"
    expose:
      - "1500"
    environment:
      - NODE_ENV=docker
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
      - sails_record__baseUrl__redbox=http://redbox:9000/redbox
      - sails_record__baseUrl__mint=https://demo.redboxresearchdata.com.au/mint
    networks:
      main:
        aliases:
          - rbportal
    entrypoint: /bin/bash -c "cd /opt/redbox-portal && node app.js"

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./dev/publication:/usr/share/nginx/html:delegated"
      - "./dev/nginx.conf:/etc/nginx/conf.d:delegated"
    expose:
      - "8080"

  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata:delegated"
      - "./dev/mongo/data/db:/data/db:delegated"
      - "./dev/log/mongo:/var/log/mongo:delegated"
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
