version: '3.1'
networks:
  main:
services:
  redboxportal:
    build: .
    image: qcifengineering/redbox-portal:latest

    ports:
       - "1500:1500"
    volumes:
       - ".:/opt/redbox-portal"
       - "/mnt/data/attachments:/attachments"
       - "/mnt/data/publication:/publication"
       - "/opt/hooks:/opt/hooks"
    expose:
       - "1500"
    environment:
      - NODE_ENV=docker
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
      - sails_record__baseUrl_redbox=http://redbox:9000/redbox
      - sails_record__baseUrl_mint=https://demo.redboxresearchdata.com.au/mint
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
     main:
       aliases:
         - rbportal
    entrypoint: /bin/bash -c "cd /opt/redbox-portal && node app.js"

  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata"
      - "/mnt/data/mongo/data/db:/data/db"
      - "/var/log/mongo:/var/log/mongo"
    networks:
      main:
        aliases:
          - mongodb
    ports:
       - "27017:27017"
